"""Added Rating to db

Revision ID: 40d7b1090987
Revises: fe166aa0fa9f
Create Date: 2019-06-30 03:16:02.736219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d7b1090987'
down_revision = 'fe166aa0fa9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('validity', sa.Integer(), nullable=False),
    sa.Column('minimalist', sa.Integer(), nullable=False),
    sa.Column('distinct_items', sa.Integer(), nullable=False),
    sa.Column('details', sa.Integer(), nullable=False),
    sa.Column('spatial_info', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')
    # ### end Alembic commands ###
