"""Added user login count

Revision ID: 60c6d9d09c93
Revises: 87f77b57795b
Create Date: 2019-06-27 00:45:14.441982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c6d9d09c93'
down_revision = '87f77b57795b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    # ### end Alembic commands ###
