"""Added user login ip

Revision ID: 87f77b57795b
Revises: 5957ec70af44
Create Date: 2019-06-27 00:43:04.688954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f77b57795b'
down_revision = '5957ec70af44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'current_login_ip')
    # ### end Alembic commands ###
